spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 83212777
          url: jdbc:mysql://127.0.0.1/helper?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#          ?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#          106.14.181.20

picConfig.url: http://172.18.150.157:8989/pictures/
picConfig.location: I:/test/
pdfConfig.location: I:/test/
fontConfig.location: I:/test/
