server:
  port: 8989
spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: yclj
          password: 83212777
          url: jdbc:mysql://106.14.181.20/helper?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

picConfig.url: http://106.14.181.20:8989/pictures/
picConfig.location: /java-project/pic/
pdfConfig.location: /java-project/pdf/
