server:
  port: 10012
spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: jlfs0728
          password: bs
          url: jdbc:oracle:thin:@192.168.10.58:1521:orcl
          driver-class-name: oracle.jdbc.OracleDriver